format: yamanifest
version: 1.0
---
work/atmosphere/yatm_d7c3c28.exe:
  fullpath: /g/data/ik11/inputs/access-om2/bin/yatm_d7c3c28.exe
  hashes:
    binhash: bd49c034de195c97ef35dddd6f0a8cda
    md5: e8a6849d153161b8e061f61373b6c0a0
work/ice/cice_auscom_3600x2700_722p_26e6159_libaccessom2_d7c3c28.exe:
  fullpath: /g/data/ik11/inputs/access-om2/bin/cice_auscom_3600x2700_722p_26e6159_libaccessom2_d7c3c28.exe
  hashes:
    binhash: 262758c569787f77cee7a073f8d4bf40
    md5: 80945878983dd0de76c442959c2a1502
work/ocean/fms_ACCESS-OM_08cf2b5_libaccessom2_d7c3c28.x:
  fullpath: /g/data/ik11/inputs/access-om2/bin/fms_ACCESS-OM_08cf2b5_libaccessom2_d7c3c28.x
  hashes:
    binhash: 9631f63ea58016289f7797c81860c6b4
    md5: b1efe5b4c11d64a33c8af1ad335fc3ac
